apiVersion: v1
kind: PersistentVolume
metadata:
  name: acme-storage
  namespace: kube-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/tf-acme/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
