# Configure Traefik static configuration
# -- Additional arguments to be passed at Traefik's binary
# All available options available on https://docs.traefik.io/reference/static-configuration/cli/
## Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
additionalArguments:
  #  - "--providers.kubernetesingress.ingressclass=traefik-internal"
  #  - "--log.level=DEBUG"
  - "--certificatesresolvers.myresolver.acme.email=triangledx@outlook.com"
  - "--certificatesresolvers.myresolver.acme.storage=acme.json"
  - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
