providers:
  file:
    # -- Create a file provider
    enabled: true
    # -- Allows Traefik to automatically watch for file changes
    watch: true
    # -- File content (YAML format, go template supported) (see https://doc.traefik.io/traefik/providers/file/)
    content: |
      certificatesResolvers:
        myresolver:
          acme:
            email: your-email@example.com
            storage: acme.json
            httpChallenge:
              # used during the challenge
              entryPoint: web
