# Refer https://artifacthub.io/packages/helm/traefik/traefik?modal=values

additionalArguments:
  - "--certificatesresolvers.myresolver.acme.email=triangledx@outlook.com"
  - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
  - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

deployment:
  additionalVolumes:
    - name: acme-storage
      emptyDir: {}

volumes:
  - name: acme-storage
    mountPath: /acme
