# Refer https://artifacthub.io/packages/helm/traefik/traefik?modal=values

additionalArguments:
  - "--certificatesresolvers.myresolver.acme.email=triangledx@outlook.com"
  - "--certificatesresolvers.myresolver.acme.storage=acme.json"
  - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

deployment:
  additionalVolumes:
    - name: acme-storage
      hostPath:
        path: /root/k3s-build/traefik/acme/acme.json
        type: File

volumes:
  - name: acme-storage
    mountPath: acme.json
